# Generated by Django 5.2 on 2025-04-22 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Categoria de Projeto', 'verbose_name_plural': 'Categorias de Projetos'},
        ),
    ]
